"""空间定位上下文的稳定输入输出契约。"""

from __future__ import annotations

from typing import Any


def _structured_error(error: Any, success: bool) -> dict[str, str] | None:
    if success and not error:
        return None
    if isinstance(error, dict):
        return {
            "code": str(error.get("code") or "localization_failed"),
            "message": str(error.get("message") or error.get("detail") or "localization failed"),
        }
    return {
        "code": "localization_failed",
        "message": str(error or "localization failed"),
    }


def _unavailable(reason: str) -> dict[str, str]:
    return {"status": "not_available", "reason": reason}


def normalize_localization_result(
    algorithm_id: str,
    raw_result: dict[str, Any] | None,
    *,
    min_inliers: int,
    elapsed_s: float | None = None,
    feature_method: str | None = None,
) -> dict[str, Any]:
    """把各算法的历史返回值转换为统一且向后兼容的结果。"""
    raw = dict(raw_result or {})
    success = bool(raw.get("success", False))

    quality = dict(raw.get("quality") or {})
    inlier_count = int(quality.get("inlier_count", raw.get("inliers", 0)) or 0)
    match_count = int(
        quality.get(
            "match_count",
            raw.get("match_count", raw.get("total_3d_points", inlier_count)),
        )
        or 0
    )
    reprojection_error = quality.get(
        "reprojection_error_px", raw.get("reprojection_error")
    )
    quality = {
        "match_count": match_count,
        "inlier_count": inlier_count,
        "reprojection_error_px": reprojection_error,
        "score": raw.get("score"),
        "quality_passed": raw.get("quality_passed"),
        "quality_score": raw.get("quality_score"),
        "quality_reasons": raw.get("quality_reasons", []),
    }

    reliable = bool(raw.get("reliable", success and inlier_count >= min_inliers))

    validations = dict(raw.get("validations") or {})
    projection = raw.get("projection_verification")
    las = raw.get("las_verification")
    if projection is not None:
        validations.setdefault("projection_consistency", projection)
    else:
        validations.setdefault(
            "projection_consistency",
            _unavailable("projection consistency was not evaluated"),
        )
    if las is not None:
        validations.setdefault("las_nearest", las)
    else:
        validations.setdefault("las_nearest", _unavailable("LAS validation was not evaluated"))
    validations.setdefault(
        "ground_truth",
        _unavailable("independent ground truth not provided"),
    )
    artifact_generation = raw.get("artifact_generation")
    if artifact_generation is not None:
        validations.setdefault("artifact_generation", artifact_generation)
    else:
        validations.setdefault(
            "artifact_generation",
            _unavailable("visual artifacts were not generated by this result"),
        )
    coordinate_transform = raw.get("coordinate_transform")
    if coordinate_transform is not None:
        validations.setdefault("coordinate_crosscheck", coordinate_transform)
    else:
        validations.setdefault(
            "coordinate_crosscheck",
            _unavailable("local coordinate transform artifacts were not generated"),
        )

    artifacts = dict(raw.get("artifacts") or {})
    for key in ("query_image", "comparison_image", "reprojection_image"):
        if raw.get(key):
            artifacts.setdefault(key, raw[key])

    timings = dict(raw.get("timings") or {})
    if elapsed_s is not None:
        timings["total_s"] = round(float(elapsed_s), 6)

    normalized = {
        "contract_version": 1,
        "algorithm_id": algorithm_id,
        "success": success,
        "reliable": reliable,
        "pose": raw.get("pose"),
        "quality": quality,
        "validations": validations,
        "artifacts": artifacts,
        "timings": timings,
        "error": _structured_error(raw.get("error"), success),
        # 兼容旧页面与历史调用方，一个发布周期后再评估移除。
        "feature_method": feature_method or raw.get("feature_method"),
        "match_method": algorithm_id,
        "inliers": inlier_count,
        "matched_points": raw.get("matched_points", []),
        "query_image": artifacts.get("query_image"),
        "comparison_image": artifacts.get("comparison_image"),
        "reprojection_image": artifacts.get("reprojection_image"),
        "projection_verification": validations.get("projection_consistency"),
        "las_verification": validations.get("las_nearest"),
        "match_count": match_count,
        "reprojection_error": reprojection_error,
        "strategy": raw.get("strategy"),
        "total_rounds": raw.get("total_rounds"),
        "iter_history": raw.get("iter_history", []),
        "total_3d_points": raw.get("total_3d_points", match_count),
        "all_candidates": raw.get("all_candidates", []),
        "coordinate_transform": validations.get("coordinate_crosscheck"),
    }
    return normalized
